### PR TITLE
VIH-10175 Refactor health check to improve startup and liveness

### PR DESCRIPTION
**Pull request by shaed-parkar**
### JIRA link (if applicable) ###

VIH-10175

### Change description ###

Refactor health check

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by oliver-scott — APPROVED** [review]
health checks seem good. It looks like this PR also fixes an issue with notifications? Might be worth adding the ticket number to the PR description, just for reference

**Comment by shaed-parkar** [comment]
> health checks seem good. It looks like this PR also fixes an issue with notifications? Might be worth adding the ticket number to the PR description, just for reference

The bug fix was merged in PR #214 . I just took a branch off that for this branch

**Review by oliver-scott — APPROVED** [review]

**Comment by shaed-parkar** [comment]
replaced with #215

**Pull request closed without merging**
